# Generated by Django 2.2.12 on 2020-05-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='postal',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
