# Generated by Django 2.2.12 on 2020-05-27 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('name', models.CharField(max_length=30)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10)),
                ('son', models.BooleanField(default=False, verbose_name='sprayed / neutered')),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('coat', models.CharField(max_length=20)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('allergies_notes', models.CharField(blank=True, max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('vaccine', models.CharField(blank=True, choices=[('rabies', 'Rabies'), ('Bordtella', 'Bordtella'), ('Canine Distemper / Parvo Combo', 'Canine Distemper / Parvo Combo'), ('Canine Influenza', 'Canine Influenza'), ('Leptospirosis (Lepto4)', 'Leptospirosis (Lepto4)'), ('Canine C3', 'Canine C3'), ('Canine C4', 'Canine C4'), ('Canine C5', 'Canine C5'), ('Canine C7', 'Canine C7'), ('Feline FVRCP group (rhino, calic, distemper)', 'Feline FVRCP group (rhino, calic, distemper)'), ('Feline Herpesvirus (FHV)', 'Feline Herpesvirus (FHV)'), ('Feline Calicivirus (FCV)', 'Feline Calicivirus (FCV)'), ('Feline Panleukopenia (FPK)', 'Feline Panleukopenia (FPK)')], max_length=45)),
                ('allergies', models.BooleanField(blank=True)),
                ('anal_gland', models.BooleanField(verbose_name='Anal Gland Issues')),
                ('arthirits', models.BooleanField(verbose_name='Arthritis')),
                ('blind', models.BooleanField(verbose_name='Blind / Poor Vision')),
                ('trachea', models.BooleanField(verbose_name='Collapsing Trachea')),
                ('deaf', models.BooleanField(verbose_name='Deaf/Poor vision')),
                ('diabetic', models.BooleanField(verbose_name='Diabetic')),
                ('standing', models.BooleanField(verbose_name='Difficulty Standing')),
                ('epileptic', models.BooleanField(verbose_name='Epileptic')),
                ('heart', models.BooleanField(verbose_name='Heart Problems')),
                ('hip', models.BooleanField(verbose_name='Hip Dysplasia')),
                ('hot', models.BooleanField(verbose_name='Hot Spots')),
                ('incontinence', models.BooleanField(verbose_name='Incontinence')),
                ('kidney', models.BooleanField(verbose_name='Kidney Disease')),
                ('moles', models.BooleanField(verbose_name='Moles & Warts')),
                ('pancreatitis', models.BooleanField(verbose_name='Pancreatitis')),
                ('ear', models.BooleanField(verbose_name='Prone to ear infection')),
                ('skin', models.BooleanField(verbose_name='Sensitive Skin')),
                ('tooth', models.BooleanField(verbose_name='Tooth Decay')),
                ('tumors', models.BooleanField(verbose_name='Tumors / Cysts')),
                ('anxiety', models.BooleanField(verbose_name='Anxiety')),
                ('cage', models.BooleanField(verbose_name='Cage Aggressive')),
                ('clippers', models.BooleanField(verbose_name='Fear of Clippers')),
                ('dryer', models.BooleanField(verbose_name='Fear of Dryer')),
                ('nail', models.BooleanField(verbose_name='Fear of nail clipping')),
                ('water', models.BooleanField(verbose_name='Fear of warter')),
                ('shedding', models.BooleanField(verbose_name='Heavy Shedding')),
                ('hernia', models.BooleanField(verbose_name='Hernia')),
                ('energy', models.BooleanField(verbose_name='High energy')),
                ('biting', models.BooleanField(verbose_name='History of biting')),
                ('leash', models.BooleanField(verbose_name='Leash required')),
                ('soiler', models.BooleanField(verbose_name='Nervous soiler')),
                ('prefumes', models.BooleanField(verbose_name='Np Perfumes')),
                ('photo', models.BooleanField(verbose_name='No public photos')),
                ('animal', models.BooleanField(verbose_name='Potential Aggression w/ animals')),
                ('people', models.BooleanField(verbose_name='Potential Aggression w/ people')),
                ('clipper_burn', models.BooleanField(verbose_name='Prone to clipper burn')),
                ('senior', models.BooleanField(verbose_name='senior pet')),
                ('table', models.BooleanField(verbose_name='Table/Kennel diver')),
                ('team', models.BooleanField(verbose_name='Team lift')),
                ('chew', models.BooleanField(verbose_name='Tends to chew')),
                ('timid', models.BooleanField(verbose_name='Timid/Shy')),
                ('barker', models.BooleanField(verbose_name='Vocal/Barker')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pets',
            },
        ),
    ]
